chore(main): release core 1.4.1
open-feature/js-sdk pull request #1040
Opened 2024-10-16 18:34 UTC by openfeaturebot

:robot: I have created a release *beep* *boop*
---

## [1.4.1](https://github.com/open-feature/js-sdk/compare/core-v1.4.0...core-v1.4.1) (2024-10-16)

### 🧹 Chore

* import type lint rule and fixes ([#1039](https://github.com/open-feature/js-sdk/issues/1039)) ([01fcb93](https://github.com/open-feature/js-sdk/commit/01fcb933d2cbd131a0f4a005173cdd1906087e18))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2024-10-17 16:16 UTC, toddbaert requested changes
Blocking for now until a few PRs are merged - next release will be a big one!

2024-10-29 15:03 UTC, toddbaert commented
@lukas-reining @beeme1mr any objections to me doing a release of all our JS artifacts today to get all the tracking stuff out?

2024-10-29 15:06 UTC, lukas-reining commented
> @lukas-reining @beeme1mr any objections to me doing a release of all our JS artifacts today to get all the tracking stuff out?

No I think they are just waiting for this, so from my side let's go for it :)

2024-10-29 15:12 UTC, beeme1mr approved these changes

2024-10-29 15:13 UTC, lukas-reining approved these changes

2024-10-29 15:22 UTC, toddbaert approved these changes

2024-10-29 15:26 UTC, merged