feat: add transaction propagation
open-feature/js-sdk pull request #212
Opened 2022-09-12 18:36 UTC by beeme1mr

Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>

2022-09-13 11:59 UTC, beeme1mr commented on src/types.ts
> +export type TransactionContext = EvaluationContext;
@toddbaert what do you think about this? We could use evaluation context but having a transaction concept type seemed nice.

2022-09-30 17:45 UTC, toddbaert commented on src/types.ts
> +   * @returns {TransactionContext} The currently defined transaction context
```suggestion
   * @returns {TransactionContext} The current transaction context
```

2022-09-30 17:56 UTC, toddbaert commented on src/open-feature.ts
> +    return this._transactionContextPropagator.getTransactionContext();
We should think about whether it's better to throw (and therefore default) if something goes wrong here, or just ignore the transaction context.

For example, if `getTransactionContext` is not a function, that will be an exception, which will cause a default.... or we could check that is a function, and return undefined. I think throwing/defaulting is PROBABLY better, but I'm not sure.

We could also do some validation at registration time like we do for the logger.

2022-09-30 17:59 UTC, toddbaert commented on src/client.ts
> +      ...OpenFeature.getTransactionContext(),
This needs to be in the try/catch now I think. `getTransactionContext()` runs user code.

2022-09-30 18:00 UTC, toddbaert requested changes
https://github.com/open-feature/js-sdk/pull/212/files#r984831394

2022-10-03 12:03 UTC, toddbaert approved these changes

2022-10-03 12:10 UTC, toddbaert commented on src/open-feature.ts
> +    return this._transactionContextPropagator.getTransactionContext();
fixed

2022-10-03 12:10 UTC, toddbaert commented on src/client.ts
> +      ...OpenFeature.getTransactionContext(),
fixed

2022-10-03 12:15 UTC, merged